# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

no_na_paste <- function(l, sep = " ") {
    .Call('tokenbrowser_no_na_paste', PACKAGE = 'tokenbrowser', l, sep)
}

